name: Plugin asset/readme update

on:
  push:
    branches:
      - main
    paths:
      - '.wordpress-org/**'
      - 'readme.txt'

jobs:
  assets:
    name: Update WordPress.org assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy assets to WordPress.org
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: albert-ai-butler
